### ISSUE TITLE
Bug fixes are welcomed

### ISSUE THREAD

**Issue by mdxabu** [mdxabu/YelanBot#1]

**Comment by diegoborbadev** [comment]
Is there a bug list to solve?

**Comment by mdxabu** [comment]
> Is there a bug list to solve?

Subject: Project Update

Dear @diegoborbadev ,

I hope this message finds you well. I am writing to inform you that currently, there are no bugs in the project. 

However, I would also like to take this opportunity to mention that if you are considering adding some new features to the project, it would be most welcome. Innovation and improvement are always beneficial and can enhance the overall functionality and user experience of the project.

Please feel free to share your ideas or suggestions regarding any potential features you might want to implement. Your input is highly valued and will be taken into consideration during the development process.

Thank you for your attention to this matter. I look forward to hearing from you soon.

Best regards,
@mdxabu

**Comment by diegoborbadev** [comment]
Do you have any new features in mind @mdxabu? Maybe we could work on them together.

**Comment by mdxabu** [comment]
> Do you have any new features in mind @mdxabu? Maybe we could work on them together.

Dear @diegoborbadev ,

I wanted to inform you that this repo will be archived anytime as the [Aiko](https://github.com/mdxabu/Aiko) repository is currently developing a discord bot. We would greatly appreciate your contribution to that project.

Best regards.
